/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IMPRIMIR_H_RPCGEN
#define _IMPRIMIR_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct imprimir_nf_1_argument {
	char *op;
	char *fecha;
	char *hora;
	char *user;
};
typedef struct imprimir_nf_1_argument imprimir_nf_1_argument;

struct imprimir_f_1_argument {
	char *op;
	char *fecha;
	char *hora;
	char *user;
	char *file;
};
typedef struct imprimir_f_1_argument imprimir_f_1_argument;

#define IMPRIMIR 99
#define IMPRIMIR_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define IMPRIMIR_NF 1
extern  enum clnt_stat imprimir_nf_1(char *, char *, char *, char *, int *, CLIENT *);
extern  bool_t imprimir_nf_1_svc(char *, char *, char *, char *, int *, struct svc_req *);
#define IMPRIMIR_F 2
extern  enum clnt_stat imprimir_f_1(char *, char *, char *, char *, char *, int *, CLIENT *);
extern  bool_t imprimir_f_1_svc(char *, char *, char *, char *, char *, int *, struct svc_req *);
extern int imprimir_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define IMPRIMIR_NF 1
extern  enum clnt_stat imprimir_nf_1();
extern  bool_t imprimir_nf_1_svc();
#define IMPRIMIR_F 2
extern  enum clnt_stat imprimir_f_1();
extern  bool_t imprimir_f_1_svc();
extern int imprimir_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_imprimir_nf_1_argument (XDR *, imprimir_nf_1_argument*);
extern  bool_t xdr_imprimir_f_1_argument (XDR *, imprimir_f_1_argument*);

#else /* K&R C */
extern bool_t xdr_imprimir_nf_1_argument ();
extern bool_t xdr_imprimir_f_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IMPRIMIR_H_RPCGEN */
