/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "imprimir.h"

bool_t
xdr_imprimir_nf_1_argument (XDR *xdrs, imprimir_nf_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->op, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->fecha, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->hora, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->user, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_imprimir_f_1_argument (XDR *xdrs, imprimir_f_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->op, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->fecha, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->hora, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->user, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->file, ~0))
		 return FALSE;
	return TRUE;
}
